services:
  todo-db:
    image: postgres:17
    container_name: todo-db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: todo_prod
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - todo-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DATABASE_USERNAME} -d todo_prod || exit 1",
        ]
      interval: 5s
      timeout: 3s
      retries: 10

  todo-backend:
    image: todo-backend
    container_name: todo-backend
    environment:
      DATABASE_URL: "jdbc:postgresql://todo-db:5432/todo_prod"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
      AWS_REGION: "${AWS_REGION:-us-east-2}"
      AWS_ACCESS_KEY: "${AWS_ACCESS_KEY}"
      AWS_SECRET_KEY: "${AWS_SECRET_KEY}"
      S3_BUCKET_NAME: "${S3_BUCKET_NAME}"
      S3_PREFIX: "${S3_PREFIX:-attachments}"
      STORAGE_TYPE: "${STORAGE_TYPE:-s3}"
    depends_on:
      todo-db:
        condition: service_healthy
    ports:
      - "${SERVER_PORT:-8080}:8080"
    networks:
      - todo-net

volumes:
  postgres-data: {}

networks:
  todo-net:
    external: true
